### ISSUE TITLE
[Bug]: not working with SLUG keyed models

### ISSUE THREAD

**Issue by rasasak** [GuavaCZ/filament-nested-resources#1]
### What happened?

I am using models keyed by slug .. not by ID

when I acces root resource on url "http://localhost:8000/admin/categories/tocene-pivo"

button linkt to create new child item is "http://localhost:8000/admin/categories//items/create?category=tocene-pivo"
there is missing model slug "tocene-pivo" between categories and items 

when I manualy try go to adress using slug "http://localhost:8000/admin/categories/tocene-pivo/items/create?category=tocene-pivo", 
there is error 
![error](https://github.com/GuavaCZ/filament-nested-resources/assets/28921659/48631cae-8081-4585-ab70-d5e158cb61d6)

when I try manualy go to adress using ID "http://localhost:8000/admin/categories/1/items/create?category=tocene-pivo"
this adress work,  but in adress and breadcrumbs is ID, instead of slug .. which is bad :(

### How to reproduce the bug

use laravel models keyed by slug

### Package Version

1.0.0-alpha.4

### PHP Version

8.2.11

### Laravel Version

10.28.0

### Which operating systems does with happen with?

Windows

**Comment by lukas-frey** [comment]
Hi, thanks for the info. You're right, I will update it as soon as possible to support keys other than IDs. :)

**Comment by lukas-frey** [comment]
@rasasak Hello Adam! I've tagged version 1.0.0-alpha.5, which includes support for custom slugs. 

To use custom slugs, you need to override the `$recordRouteKeyName` in your `NestedResource`, such as:
```php
protected static ?string $recordRouteKeyName = 'slug';
```

and modify your `{record}` parameters in your `getPages` method, for example:
```php
public static function getPages(): array
{
    return [
        'index' => Pages\ListSongs::route('/'),
        'create' => Pages\CreateSong::route('/create'),
        'edit' => Pages\EditSong::route('/{record:slug}/edit'),
    ];
}
```

Let me know if anything is missing.
