### ISSUE TITLE
[Bug]: Create modal causes route not found error

### ISSUE THREAD

**Issue by acepoblete** [GuavaCZ/filament-nested-resources#11]
### What happened?

When you have a nested resource that does not have a create page, the create action on the list page causes a route not found error.

### How to reproduce the bug

Create a nested resource then comment out the create page route. 

### Package Version

1.0.0-alpha.7

### PHP Version

8.2

### Laravel Version

10

### Notes

I think the solution is to check to see if there is a create page on the resource before setting the action URL on the `configureCreateAction` method.

` 
if (static::getResource()::hasPage('create')) {
      $action->url(static::getResource()::getUrl('create', $this->getRouteParameterIds()));
}
`

**Comment by lukas-frey** [comment]
@acepoblete Thanks :) Will release a bugfix today

**Comment by lukas-frey** [comment]
Fixed in release [1.0.0-alpha.8](https://github.com/GuavaCZ/filament-nested-resources/releases/tag/1.0.0-alpha.8)
