### ISSUE TITLE
[Bug]: Incorrect urls generated when primaryKey is not "id"

### ISSUE THREAD

**Issue by francescverdu** [GuavaCZ/filament-nested-resources#12]
### What happened?

I have a database where primaryKeys aren't "id", but "nID"

I can do  laravel  work with it simply using this statement in models:
`    protected $primaryKey = 'nID';`

But when using nested-resources the urls that are generated doesn't have the parent levels nIDs on it (two slashes appear together)

I was guessing that the package assumes that primary key will be "id" and this returns a null value on my instances, so I tested a workaround in my models:
```
public function getIdAttribute()  {
    return $this->nID;
}

```

and it worked!

I hope this will help debuging the alfa package.

### How to reproduce the bug

If you create or use a database with non-id primary keys you will experience the issue simply making a nested resource.

### Package Version

1.0@alpha

### PHP Version

8.1.8

### Laravel Version

10.10

**Comment by lukas-frey** [comment]
@francescverdu Hello, thank you for the bug report! Could you try setting the `$recordRouteKeyName` property on your resource to nID? I think that should work.

If not I'll have a look into it when I find some spare time. :)

**Comment by francescverdu** [comment]
Yeah, that solves the problem, and no need to create the additional model properties. Thanks a lot.

I can't find any documentation about $recordRouteKeyName, its seems it's an internal property or so. What is the menaning and purpose of this variable?

Anyway, I think that in order to construct the nesting urls the method used should be  $model->getKeyName() so nothing else should be necessary IMO

**Comment by lukas-frey** [comment]
> Yeah, that solves the problem, and no need to create the additional model properties. Thanks a lot.
> 
> I can't find any documentation about $recordRouteKeyName, its seems it's an internal property or so. What is the menaning and purpose of this variable?
> 
> Anyway, I think that in order to construct the nesting urls the method used should be $model->getKeyName() so nothing else should be necessary IMO

Yeah, I'll have to recheck. There's places where it still reads `id` only, so `$recordRouteKeyName` wouldn't even work.

It's a filament property, which I thought is meant to modify the route key even within Filament. That's why it's not documented in the plugin itself.

**Comment by AHMED-GAMAL-AG** [comment]
I have the same problem adding this key solved the problem for me
`protected static ?string $recordRouteKeyName = 'Id';` 

i was getting 404 before on the edit, create

**Comment by lukas-frey** [comment]
Hello, I'm closing this in favor of the newly released production version. If you still encounter any issues with the plugin, please feel free to open a new issue.
