### ISSUE TITLE
[Bug]: getTableQuery in list view of child resources are not filtered.

### ISSUE THREAD

**Issue by acepoblete** [GuavaCZ/filament-nested-resources#13]
### What happened?

When you are loading up the list view table, you see every record in the database instead of the records being filtered by their parent record. 

### How to reproduce the bug

Create a root resource and a corresponding child resource in your app.  Create two root records RootA and RootB. On record A, navigate to the child resource and create a new record ChildA.  Attempt to do the same for RootB.  You will notice that when you are on the child resource for RootB, you will see that ChildA is visible in the table.

### Package Version

1.0.0-alpha.8

### PHP Version

8.1

### Laravel Version

10

### Notes

I think the getTableQuery method needs to be extended in the NestedResource class.

**Comment by lukas-frey** [comment]
Thanks! I wasn't entirely sure whether I should even support these stand-alone list views, since I think using a relation manager makes the most sense. Will be fixed in the next release :)

**Comment by acepoblete** [comment]
Can you elaborate a bit more on how you envision things working?

**Comment by lukas-frey** [comment]
> Can you elaborate a bit more on how you envision things working?

@acepoblete Initially I only added support for these index views to make the plugin work easier "out of the box" with less steps required for a set up.

If you remove the index page (or just comment it out) from your Child Resource's `getPages` method, the plugin will only use the relation manager as the "index" page. So basically the edit page of the parent will become the index page of each child record.

**Comment by lukas-frey** [comment]
I still need to do a refactor of the whole package, because right now it's in a very experimental state and I think a lot of things could have been developed in a easier, more flexible and straightforward way than it is now. 

I hope to do that before the first production-ready release.

**Comment by lukas-frey** [comment]
Hello, I'm closing this in favor of the newly released production version. If you still encounter any issues with the plugin, please feel free to open a new issue.
