### ISSUE TITLE
[Bug]: Looks like no support for manyToMany

### ISSUE THREAD

**Issue by StaffCollab** [GuavaCZ/filament-nested-resources#14]
### What happened?

I have three tables
-campaigns (with id column)
-teams (with id column)
-campaigns_teams (pivot table with two foreign keys)

Now, I have a belongsToMany relationship set up on both Models, but I am getting an error when using this package.

Here is the error

Guava\Filament\NestedResources\Ancestor::getRelatedModel(): Return value must be of type Illuminate\Database\Eloquent\Model, Illuminate\Database\Eloquent\Collection returned

### How to reproduce the bug

Create any many-to-many relationship and test this package.

### Package Version

v3.0.0-alpha8

### PHP Version

8.1

### Laravel Version

10

**Comment by lukas-frey** [comment]
Hi, yes that's currently not supported since it's not possible to know the parent record if it can be multiple records.

**Comment by lukas-frey** [comment]
Hello, I'm closing this in favor of the newly released production version. If you still encounter any issues with the plugin, please feel free to open a new issue.
