### ISSUE TITLE
[Bug]: ForceDeleteAction generates error on NestedEditRecord class

### ISSUE THREAD

**Issue by rubenlopezgea** [GuavaCZ/filament-nested-resources#15]
### What happened?

When using SoftDeletes, ForceDeleteAction asks for an index route

### How to reproduce the bug

Use a Resource with `--soft-delete` enabled as Child.

### Package Version

1.0.0-alpha.8

### PHP Version

8.3.0

### Laravel Version

10.10

### Which operating systems does with happen with?

macOS

**Comment by lukas-frey** [comment]
Thank you for the report @rubenlopezgea ! I couldn't reproduce the specific error you mentioned, but the ForceDeleteAction wasn't implemented anyways. It should be working in the latest version now.
