### ISSUE TITLE
[Bug]: When view is enabled the breadcrumbs link is still to edit page...

### ISSUE THREAD

**Issue by StaffCollab** [GuavaCZ/filament-nested-resources#16]
### What happened?

I think that if we have a view page, the breadcrumbs should link to the view page (which is the default for clicking on the record itself), not the edit link that it is currently linking to.

Is there any way to overwrite it?

### How to reproduce the bug

just make a nested rescource with the --view flag

### Package Version

3.x

### PHP Version

8.3

### Laravel Version

10

**Comment by lukas-frey** [comment]
Currently the it opens the same page you're viewing: so if you're on an edit page, it should open also on edit page, if you're on a view page, it should open in a view page also.

**Comment by lukas-frey** [comment]
Hello, I'm closing this in favor of the newly released production version. If you still encounter any issues with the plugin, please feel free to open a new issue.
