### ISSUE TITLE
[Bug]: can't get parent model id

### ISSUE THREAD

**Issue by cobraprojects** [GuavaCZ/filament-nested-resources#18]
### What happened?

I should be able to get parent model to perform some queries
I did't find a way to get it while createing new nasted record

### How to reproduce the bug

can't get parent model id

### Package Version

1.0.0-alpha.8

### PHP Version

8.2

### Laravel Version

10.0

**Comment by jinbatsu** [comment]
Same here, I don't know how to get parent model id? Is there any method?

**Comment by cobraprojects** [comment]
> Same here, I don't know how to get parent model id? Is there any method?

I got it with this ugly code
```
fn ($livewire) => Subject::find($livewire->getRouteParameterIds()[0])->stages()->pluck('name', 'stages.id')
```

**Comment by jinbatsu** [comment]
Well OK thanks for the info, I get this with laravel request route:
`$parentId = request()->route('jobRecord');`
**job** is my parent Resource name.

Because in my case I want to get the parentId without using Clousure, some of form field can not implement clousure, specificly MoneyInput plugin.

**Comment by lukas-frey** [comment]
You can use `getAncestorRecord()`, which will return an array with a key => value item, where the key is the foreign key on the current model and the value is the ID of the parent record.

I know it's an ugly way, I'll need to refactor the whole plugin, I just couldn't find time to do so properly.

**Comment by lukas-frey** [comment]
Hello, I'm closing this in favor of the newly released production version. If you still encounter any issues with the plugin, please feel free to open a new issue.
