### ISSUE TITLE
[Bug]: ManageRelatedRecords pages have blank ancestor route paramaters

### ISSUE THREAD

**Issue by alec-lefors** [GuavaCZ/filament-nested-resources#20]
### What happened?

My resource has a couple subnav items through ManageRelatedRecords, the links in the subnav are missing the resource's root parameter causing a 404. However, the routes themselves are fine and can be accessed otherwise.

### How to reproduce the bug

https://filamentphp.com/docs/3.x/panels/resources/getting-started#resource-sub-navigation

1. Create resource sub navigation and relation page
2. Click on the subnav

### Package Version

1.0.0-alpha.9

### PHP Version

8.3

### Laravel Version

10

### Which operating systems does with happen with?

Linux

**Comment by lukas-frey** [comment]
Hi @alec-lefors ManageRelatedRecords isn't supported by the package sadly.

**Comment by lukas-frey** [comment]
We've added support for RelationPages in the new beta version. Feel free to test it out, but please keep in mind that some bugs may still occur until we release version 1.0.
