### ISSUE TITLE
[Bug]: Can't install the package

### ISSUE THREAD

**Issue by AHMED-GAMAL-AG** [GuavaCZ/filament-nested-resources#22]
### What happened?

composer require guava/filament-nested-resources

In PackageDiscoveryTrait.php line 331:

  Could not find a version of package guava/filament-nested-resources matching your minimum-stability (stable). Require it with an explicit version cons          
  traint allowing its desired stability.

require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-audit] [--audit-format AUDIT-FORMAT] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>...]

### How to reproduce the bug

i had to use  `composer require guava/filament-nested-resources:dev-main` instead

### Package Version

default

### PHP Version

8.2.1

### Laravel Version

10

**Comment by lukas-frey** [comment]
https://github.com/GuavaCZ/filament-nested-resources/issues/19#issuecomment-1930235600
