### ISSUE TITLE
[Bug]: Cant install using composer require guava/filament-nested-resources

### ISSUE THREAD

**Issue by AHMED-GAMAL-AG** [GuavaCZ/filament-nested-resources#24]
### What happened?

![image](https://github.com/GuavaCZ/filament-nested-resources/assets/76778937/631cc6f3-56e8-483b-955b-67df1ddce771)

### How to reproduce the bug

when i use composer require guava/filament-nested-resources:dev-alpha it can be installed now 

### Package Version

default

### PHP Version

8.2.1

### Laravel Version

10.10

**Comment by lukas-frey** [comment]
That's because it's an alpha version. If you want to use it (not recommended for production use), you need to have minimum-stability set to `dev` in your composer config.
