### ISSUE TITLE
[Bug]: Unable to get nested Create to work in new release

### ISSUE THREAD

**Issue by maesklaas** [GuavaCZ/filament-nested-resources#31]
### What happened?

I had successfully implements an earlier version of this package. I was now trying to migrate to the 1.0.0 version. But i am not able to manage this yet.

Is there a example of the RelationManager implementation?

I would say i followed the steps of the documentation, but still have some issues.
Edit of a nested resource is now working. But it has a not nested url. Is this an intendent change or or am i missing some configuration?
Create is redirecting to a nested url but it is showing an 404 while the route is registered in laravel.

Looks like I'm missing some information. Could you help me to get it to work and probably improve the documentation for others as well?

### How to reproduce the bug

```
class ArtistResource extends Resource
{
    use NestedResource;

    public static function getAncestor(): ?Ancestor
    {
        return null;
    }
    
    public static function getRelations(): array
    {
        return [
            ArtistAlbumRelationManager::class,
        ];
    }
   //...

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListArtists::route('/'),
            'create' => Pages\CreateArtist::route('/create'),
            'edit' => Pages\EditArtist::route('/{record}/edit'),
            'albums.create' => CreateArtistAlbum::route('/{record}/albums/create'),
        ];
    }
}
```

```
class ArtistAlbumResource extends Resource
{
    use NestedResource;

    public static function getAncestor(): ?Ancestor
    {
        return Ancestor::make('albums', 'artist');
    }
   //...
    
    public static function getPages(): array
    {
        return [
            'edit' => Pages\EditArtistAlbum::route('/{record}/edit'),
        ];
    }
}
```
```
class CreateArtistAlbum extends CreateRelatedRecord
{
    use NestedPage;
   //...
 }
```
```
class EditArtistAlbum extends EditRecord
{
    use NestedPage;
   //...
}
```

```
class ArtistAlbumsRelationManager extends RelationManager
{
    use NestedRelationManager;
    //...
}
```

### Package Version

1.0.0

### PHP Version

8.3.0

### Laravel Version

11

**Comment by lukas-frey** [comment]
Hi, thanks for the bug report.

The `CreateArtistAlbum` page needs a `static protected string $relationship` property set to the relationship name it uses, in your case it would be `albums`. (Basically you can copy the property from the `ArtistAlbumsRelationManager`, which has it included by default if you used the filament generator command for it.)
This is missing in the documentation, I need to add it.

Where did you create the `CreateArtistAlbum` page? It needs to be a page in `ArtistResource/Pages`, NOT in `AlbumResource/Pages` (the resource property needs to be set to `ArtistResource`).

Regarding the URL change, yes it no longer shows the "nested path" in the URL - otherwise recursive nested resources were not possible. Plus it allowed the codebase to be simplified a lot.

And regarding the documentation I'm not entirely happy with it either. If you have any suggestions on how to improve it, feel free to share or make a PR. :)

**Comment by maesklaas** [comment]
Hi,

I added the relationship property. The `CreateArtistAlbum` was already part  of the `ArtistResource/Pages` folder.

The create is still a nested url on the parent resource by design? Unfortunally this create url is still returning an 404 at the moment. Any clue what else could be missing at the moment? An very basic complete example would be usefull as well.

The EditArtistAlbum should be in `AlbumResource/Pages`?

**Comment by lukas-frey** [comment]
@maesklaas Yes, the URLs are supposed to be like that.

I've had the demo project requested by multiple people already, so [here](https://github.com/GuavaCZ/filament-nested-resources-demo) is a basic example (similar to the one in the documentation) with a Artist -> Album -> Song demo.

I hope it helps to showcase how the package is supposed to be used. :) Also added the missing `$relationship` property part to the documentation.

Feel free to message if you don't understand something in the demo.

**Comment by maesklaas** [comment]
Hi, i was able to get it up and running. 

I have only one issue left on a specific nested relation which has a translatable field.
Spatie filament translatable has a Translatable trait for all page types like CreateRecord. But this one doesn't work for CreateRelatedRecord there the $resource is the parent and not the resource itself. Is there an easy way to get around this issue?

**Comment by lukas-frey** [comment]
We have a custom `Translatable` trait for CreateRelatedRecord for Spatie's translation package.
